Feature/paypal ppcp
activemerchant/active_merchant pull request #3778
Opened 2020-10-02 12:52 UTC by TariqAleem

**PayPal Commerce Platform - Integrated Features**

- PayPal Checkout: Capture only

- PayPal Checkout: Authorize and Capture

- Advanced Card Payments

- Checkout using Billing Agreements

2020-10-02 19:55 UTC, jessiagee commented
@TariqAleem Looks like Travis CI build failed with checks

2020-10-06 14:02 UTC, jessiagee requested changes
Add .idea to your global .gitignore file so that they aren't picked up by git to add to the project - https://stackoverflow.com/questions/39013880/how-to-set-global-gitignore-file-in-android-studio/41705045#41705045

2020-10-08 14:43 UTC, TariqAleem commented on .gitignore
> +.idea/*
Hello @jessiagee , we have currently removed .idea/ from .gitignore, so should we add it ?

2020-10-08 14:58 UTC, TariqAleem commented on .ruby-gemset
> +active_merchant_ppcp
Yes this can be removed.

2020-10-13 11:41 UTC, TariqAleem reviewed
Changes done please review

2021-06-17 13:33 UTC, jessiagee commented
This was integrated in AGX

2021-06-17 13:33 UTC, closed without merging