Adyen: Truncating order_id and remote test
activemerchant/active_merchant pull request #4036
Opened 2021-07-12 14:40 UTC by yyapuncich

EVS-830
Needs to be less than 80 characters for Google Pay transactions

Unit:
Finished in 9.874792 seconds.
----------------------------------------------------------------------------------------------------------------------------------------
4798 tests, 73809 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
----------------------------------------------------------------------------------------------------------------------------------------
485.88 tests/s, 7474.49 assertions/s
Running RuboCop...
Inspecting 705 files

705 files inspected, no offenses detected

Remote:
Finished in 115.285449 seconds.
----------------------------------------------------------------------------------------------------------------------------------------
103 tests, 399 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
----------------------------------------------------------------------------------------------------------------------------------------
0.89 tests/s, 3.46 assertions/s

Adyen: replaced truncate method with slice

truncate method is rails method and slice is Ruby

rm puts

2021-07-12 15:46 UTC, shasum approved these changes
LGTM!

2021-07-13 13:45 UTC, yyapuncich commented on lib/active_merchant/billing/three_d_secure_eci_mapper.rb
> -
I only edited this file bc the unit tests showed rubocop errors. is that ok?

2021-07-13 14:19 UTC, meagabeth requested changes
Overall this looks great - nice and clean! I would recommend adding a unit test to verify that we are sending the truncated value when the order_id is longer than 80 characters.

2021-07-13 19:06 UTC, meagabeth approved these changes
Looks amazing and tests are all passing! Go forth 🚢

2021-07-13 19:18 UTC, merged