PayArc: Formatting CC month and adding tax_rate
activemerchant/active_merchant pull request #4053
Opened 2021-07-21 19:07 UTC by jessiagee

* Fixed an issue with CC months not working for '01', '02', etc.
* Added `tax_rate` to the charges allowed list

Loaded suite test/unit/gateways/pay_arc_test

15 tests, 46 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Loaded suite test/remote/gateways/remote_pay_arc_test

19 tests, 48 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
94.7368% passed

bundle exec rake test:local
4836 tests, 73901 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Running RuboCop...

707 files inspected, no offenses detected

2021-07-21 19:27 UTC, jessiagee commented
@senthil-code Hey Senthil, do you see any issues here?

2021-07-21 20:58 UTC, meagabeth requested changes
These changes look good, but I think we should revise the unit test to show that the month being sent is being modified to two digits. As of now, we tell it to respond with a successful response and so therefore it succeeds, but we're not showing that the month is being adjusted.

2021-07-22 08:02 UTC, cdm-83 commented
> @senthil-code Hey Senthil, do you see any issues here?

@jessiagee - Looks fine, No issues.

2021-07-22 15:34 UTC, jessiagee commented
> These changes look good, but I think we should revise the unit test to show that the month being sent is being modified to two digits. As of now, we tell it to respond with a successful response and so therefore it succeeds, but we're not showing that the month is being adjusted.

Thanks, I moved it from unit to remote (wasn't paying attention to which one I put it in, sorry!) and also I've moved https://github.com/activemerchant/active_merchant/pull/4054 into here to consolidate these small fixes into one update.

2021-07-22 19:25 UTC, meagabeth approved these changes
Looks good! 1 failing remote test due to account setup, but that was expected per our chat.

2021-07-22 19:25 UTC, meagabeth commented on test/remote/gateways/remote_pay_arc_test.rb
> +  def test_failed_three_digit_card_exp_month
nice!

2021-07-22 19:30 UTC, merged