Redsys: Route MIT Exemptions to webservice endpoint
activemerchant/active_merchant pull request #4081
Opened 2021-08-10 21:22 UTC by curiousepic

For MIT-exempt transactions, automatically add the DIRECTPAYMENT field
and route them to the webservice endpoint as a trataPeticion for proper
handling.

Also add flag to force routing to the webservice endpoint and renames
some methods and values for clarity and accuracy.

2021-08-12 15:15 UTC, esmitperez commented on test/remote/gateways/remote_redsys_sha256_test.rb
> +    options = @options.merge(execute_threed: true)
what's behind the removal of terminal 12?

2021-08-17 15:14 UTC, Carrigan requested changes
Rubocop has a couple of failures related to the change that we should take care of before merging, but otherwise the changes all look good and make sense to me :+1: All remote tests pass the same as master.

2021-08-17 16:04 UTC, curiousepic commented
Thanks, addressed the Rubocop alerts.

2021-08-17 19:55 UTC, Carrigan approved these changes
Thanks for fixing the linting errors! LGTM :+1:

2021-08-23 17:19 UTC, esmitperez commented
I was able to run remote tests! I forgot to adjust the AM hash 🙈 . 

I don't recall the exact steps to reproduce fix in Postman, but we can pair on it

2021-08-31 17:01 UTC, Carrigan approved these changes

2021-08-31 17:04 UTC, closed without merging