Ce 2052 global collect airline data
activemerchant/active_merchant pull request #4187
Opened 2021-11-08 20:21 UTC by naashton

2021-11-08 22:40 UTC, dsmcclain submitted a review, later dismissed
The two failing tests I get are:
`test_successful_purchase_with_installments`
`test_successful_purchase_with_airline_data`

The installments test is failing on master as well, so I'm not really worried about that at the moment.

The airline_data test fails with a timeout, like you described. Have you reached out to the gateway about this? It could just be a limitation of their sandbox, but considering that these are the exact fields that this PR is addressing it would nice to at least have an answer from them about why the airline data might not be working.

2021-11-09 15:35 UTC, naashton commented
Erik is linking me up with Igenico's POC to see why we are getting a time-out. I'll re-request review once we are able to get something to work with.

2021-12-21 16:33 UTC, jessiagee commented on lib/active_merchant/billing/gateways/global_collect.rb
> +          leg['airlineClass'] = fl[:carrier_code] if fl[:airline_class]
Should this be `fl[:airline_class] if fl[:airline_class]` ?

2021-12-21 16:34 UTC, jessiagee commented on lib/active_merchant/billing/gateways/global_collect.rb
> +          leg['conjunctionTicket'] = fl[:conjuction_ticket] if fl[:conjction_ticket]
Typos - `fl[:conjunction_ticket] if fl[:conjunction_ticket]`

2021-12-21 16:35 UTC, jessiagee requested changes
Some typos to clean up

2021-12-21 18:17 UTC, jessiagee approved these changes
bundle exec rake test:local

5010 tests, 74788 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Running RuboCop...

725 files inspected, no offenses detected

Loaded suite test/unit/gateways/global_collect_test

31 tests, 154 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Loaded suite test/remote/gateways/remote_global_collect_test

Failure: test_successful_purchase_with_installments(RemoteGlobalCollectTest) -- failing on master as well

26 tests, 62 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
96.1538% passed

2021-12-21 18:19 UTC, merged