GlobalCollect: Update Production Endpoint
activemerchant/active_merchant pull request #4196
Opened 2021-11-17 14:59 UTC by naashton

The existing endpoint for GlobalCollect is no longer supported by
Ingenico. Conversations with the gateway indicate that requests sent to
the current prod endpoint are being redirected to the new endpoint, but
there is no concrete answer on this.

CE-2116

Unit: 30 tests, 148 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Remote: 26 tests, 62 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
96.1538% passed

2021-11-17 16:01 UTC, meagabeth approved these changes
Simple enough! Majority of tests pass, 1 unrelated remote test failure also failing on `master` branch. 🚀

2022-01-06 23:48 UTC, jessiagee requested changes

2022-01-06 23:48 UTC, jessiagee commented on test/remote/gateways/remote_global_collect_test.rb
> +    options = @preprod_options.merge(order_id: rand(1000), requires_approval: true)
We should remove `requires_approval` here

2022-01-07 16:32 UTC, jessiagee approved these changes
Looks good and tests are passing!

2022-01-07 16:32 UTC, merged