Rapyd: Change parameter key name
activemerchant/active_merchant pull request #4514
Opened 2022-07-27 07:01 UTC by ajawadmirza

Change stored credential key name from `original_network_transaction_id` to `network_transaction_id` as per the standard framework of stored credential.

SER-126

Unit:
5268 tests, 76153 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Rubocop:
746 files inspected, no offenses detected

Remote:
28 tests, 52 assertions, 15 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
46.4286% passed

2022-07-27 09:09 UTC, drkjc requested changes
@ajawadmirza Thank you for making this change! I wish I had caught this earlier and appreciate all the work you're doing for this!  Just a quick CHANGELOG fix and I'll merge.

2022-07-28 08:44 UTC, drkjc commented on CHANGELOG
> +* Rapyd: change key name to `network_transaction_id` [ajawadmirza] 4514
@ajawadmirza Also just noticed the first word after the colon should be capitalized.

2022-07-28 10:30 UTC, ajawadmirza commented on CHANGELOG
> +* Rapyd: change key name to `network_transaction_id` [ajawadmirza] 4514
Fixed 👍

2022-07-28 10:50 UTC, drkjc approved these changes
Still getting 15 failing tests, but they are unrelated to the work here. Merging. 

28 tests, 52 assertions, 15 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
46.4286% passed

2022-07-28 10:52 UTC, closed without merging