Shift4: Capture field changes and hardcode header values
activemerchant/active_merchant pull request #4528
Opened 2022-08-09 08:00 UTC by ajawadmirza

Capture changes to add card present field, use same invoice number as authorization, and hardcode header values.

SER-223
SER-226

Remote:
16 tests, 37 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Unit:
5273 tests, 76175 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Rubocop:
746 files inspected, no offenses detected

2022-08-09 20:11 UTC, drkjc requested changes
@ajawadmirza Sorry to make you do this, but there's a lowercase word in the CHANGELOG that needs to be capitalized. Otherwise, everything looks great!

2022-08-09 20:11 UTC, drkjc commented on CHANGELOG
> +* Shift4: add card `present` field, use previous transaction authorization for capture, and hardcode header values [ajawadmirza] #4528
Capitalize the `a` in `add`

2022-08-10 07:00 UTC, ajawadmirza commented on CHANGELOG
> +* Shift4: add card `present` field, use previous transaction authorization for capture, and hardcode header values [ajawadmirza] #4528
Thanks, change is updated 👍

2022-08-10 09:27 UTC, ajawadmirza commented
I have also added card present field for refund as this ticket (SER-222) is also related to this PR. 

https://github.com/activemerchant/active_merchant/pull/4528/files#diff-fc67ccfe1e4c5ec05676588bd97cee17d72d6ea9a1f84ede7c2f98e0f947e8c9R119

2022-08-10 14:16 UTC, drkjc approved these changes
Nice work, Jawad. Looks great.

2022-08-10 14:23 UTC, closed without merging