CardConnect: Add Stored Credential
activemerchant/active_merchant pull request #4609
Opened 2022-10-19 08:15 UTC by ajawadmirza

Added stored credential implementation and fixed `ecomind` field to pass any valid value as per the documentation (`T`, `R`, `E`) along with remote and unit tests.

SER-376

Unit:
5363 tests, 76675 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed

Rubocop:
750 files inspected, no offenses detected

Remote:
25 tests, 57 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed

2022-10-20 14:49 UTC, naashton requested changes
The stored credentials implementation looks good. Just change how we handle the `:ecomind` and this should be good.

2022-10-20 16:49 UTC, ajawadmirza commented on lib/active_merchant/billing/gateways/card_connect.rb
> +        post[:ecomind] = options[:ecomind] if options[:ecomind]
Thanks @naashton , I have applied the changes.

2022-10-21 12:40 UTC, naashton approved these changes

2022-10-21 12:40 UTC, naashton commented on lib/active_merchant/billing/gateways/card_connect.rb
> +                         end
This looks good!

2022-10-21 12:40 UTC, merged