Adyen: Add the store field
activemerchant/active_merchant pull request #4878
Opened 2023-08-30 01:22 UTC by yunnydang

Local:
5589 tests, 77761 assertions, 0 failures, 19 errors, 0 pendings, 0 omissions, 0 notifications 99.66% passed

Unit:
111 tests, 583 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed

Remote:
134 tests, 447 assertions, 11 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 91.791% passed

Note: 
The reason why I didn't pursue a remote test for this change is because it requires an actual store reference to be sent, otherwise it'll return an invalid store error message and code. Not sure if the sandbox supports it, but we'd have to create a store, then grab the reference, and send that in our remote test in order to not have a failing test.

2023-09-01 21:35 UTC, rachelkirk requested changes
I am hesitant to approve if we can't get a passing remote test. This may put us in the situation of having to do a quick revert which is never fun. 

In looking into this further, the docs provided in the ticket reference the [Checkout API](https://docs.adyen.com/api-explorer/Checkout/latest/overview) but I believe we are integrated with the [Classic API](https://docs.adyen.com/api-explorer/Payment/68/post/authorise) which you can verify by looking at the endpoints we're hitting in the transcripts. We hit /authorise and /capture and in the newer Checkout API the main endpoint is /payments. All this to say, we need to verify if `store` is even supported in the Classic API before moving forward.

2023-09-05 19:53 UTC, yunnydang commented
> I am hesitant to approve if we can't get a passing remote test. This may put us in the situation of having to do a quick revert which is never fun.
> 
> In looking into this further, the docs provided in the ticket reference the [Checkout API](https://docs.adyen.com/api-explorer/Checkout/latest/overview) but I believe we are integrated with the [Classic API](https://docs.adyen.com/api-explorer/Payment/68/post/authorise) which you can verify by looking at the endpoints we're hitting in the transcripts. We hit /authorise and /capture and in the newer Checkout API the main endpoint is /payments. All this to say, we need to verify if `store` is even supported in the Classic API before moving forward.

The classic version does seem to support the store field found [here](https://docs.adyen.com/api-explorer/Payment/68/post/authorise#request-store)

2023-09-07 14:13 UTC, rachelkirk commented
> The classic version does seem to support the store field found [here](https://docs.adyen.com/api-explorer/Payment/68/post/authorise#request-store)

Thanks for verifying this! Were you able to connect with Adyen on how we could get a passing remote test, or perhaps attempt to test via Postman? I don't know that your results would be any different but it's an option to try it with the whole flow.

2023-09-08 18:04 UTC, aenand approved these changes
LGTM 🚀

2023-09-08 19:05 UTC, closed without merging