Redsys: Update to $0 verify
activemerchant/active_merchant pull request #4944
Opened 2023-11-03 15:39 UTC by almalee24

Remote:
22 tests, 54 assertions, 3 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 86.3636% passed

Unit:
34 tests, 117 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed

2023-11-03 20:13 UTC, curiousepic commented on test/remote/gateways/remote_redsys_test.rb
> +    assert_equal 'SIS0007 ERROR', void.message
I think these same changes are needed for the `sha256` version of the remote tessts as well

2023-11-03 20:15 UTC, curiousepic requested changes
I think this needs one more test change, but after that should be GTG

2023-11-20 15:04 UTC, curiousepic approved these changes
Thanks - sorry for late re-approval

2023-11-20 15:21 UTC, aenand commented
Should we also make this update to Redsys Rest?

2023-11-28 17:22 UTC, almalee24 commented
> Should we also make this update to Redsys Rest?

Just seeing this but I'll create a separate ticket to update RedsysRest.

2023-11-28 18:07 UTC, merged