Stripe and Stripe PI: add headers to response body
activemerchant/active_merchant pull request #5185
Opened 2024-07-17 20:36 UTC by yunnydang

This adds some of the header fields to the response body object using the handle_response override.

Local:
5962 tests, 79990 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Stripe unit:
146 tests, 769 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Stripe remote:
77 tests, 328 assertions, 10 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
87.013% passed

Stripe PI Unit:
61 tests, 315 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Stripe PI Remote:
95 tests, 427 assertions, 3 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
96.8421% passed

2024-07-22 21:06 UTC, jcreiff requested changes
Hey @yunnydang this is looking promising! I think it may need a little bit of tweaking though:

The way it is currently written, we will only set `@response_headers` when the response is successful (in the HTTP 200 range). Otherwise, we skip the `response.each_header.to_h` logic.

My understanding of these fields we want to surface is that they will be more useful for failed transactions (ie, I don't think anyone is concerned about whether or not they should retry after a successful purchase 😁), so I think we need to be able to grab the headers when we hit the `else raise ResponseError.new` path too 🤔 

I pulled down your branch and did some poking around with `byebug` to confirm my suspicion about the above, and sure enough, if I change the payment method to `@declined_payment_method` in your remote test, then we do skip over the `when 200...300` block of the case statement in `handle_response`, but **only** on the POST to `/payment_intents`. 

However! The test still passes in that scenario because that purchase request is preceded by a POST to `/payment_methods` (or `/tokens`), and when we handle that initial response, we are storing the headers in the `@response_headers` instance variable. This means those headers are available the second time we go through `add_header_fields`, even though we haven't updated `@response_headers` with info from the second response.  A randomly selected txn id that illustrates this kind of  sequence is `8Q3Hpae1p6HNz7hLLzB1CJcFkAR`, but I think this would happen to any transaction where we receive a `200` followed by a `402`

2024-07-22 21:08 UTC, jcreiff commented
One more thought - should we also add test coverage for Stripe (not PI) since `handle_response` and `parse` are shared logic between the two gateways?

2024-07-23 16:22 UTC, yunnydang commented
> Hey @yunnydang this is looking promising! I think it may need a little bit of tweaking though:
> 
> The way it is currently written, we will only set `@response_headers` when the response is successful (in the HTTP 200 range). Otherwise, we skip the `response.each_header.to_h` logic.
> 
> My understanding of these fields we want to surface is that they will be more useful for failed transactions (ie, I don't think anyone is concerned about whether or not they should retry after a successful purchase 😁), so I think we need to be able to grab the headers when we hit the `else raise ResponseError.new` path too 🤔
> 
> I pulled down your branch and did some poking around with `byebug` to confirm my suspicion about the above, and sure enough, if I change the payment method to `@declined_payment_method` in your remote test, then we do skip over the `when 200...300` block of the case statement in `handle_response`, but **only** on the POST to `/payment_intents`.
> 
> However! The test still passes in that scenario because that purchase request is preceded by a POST to `/payment_methods` (or `/tokens`), and when we handle that initial response, we are storing the headers in the `@response_headers` instance variable. This means those headers are available the second time we go through `add_header_fields`, even though we haven't updated `@response_headers` with info from the second response. A randomly selected txn id that illustrates this kind of sequence is `8Q3Hpae1p6HNz7hLLzB1CJcFkAR`, but I think this would happen to any transaction where we receive a `200` followed by a `402`

Thanks for pointing out this insight @jcreiff ! Im thinking that with the use case like you mentioned where its most useful for failing transactions, do you think it might be better to move the logic to grab headers only for failing transactions? I think that would be something we can explore instead of adding headers to both fail/successful

2024-07-23 18:06 UTC, yunnydang commented
> > Hey @yunnydang this is looking promising! I think it may need a little bit of tweaking though:
> > The way it is currently written, we will only set `@response_headers` when the response is successful (in the HTTP 200 range). Otherwise, we skip the `response.each_header.to_h` logic.
> > My understanding of these fields we want to surface is that they will be more useful for failed transactions (ie, I don't think anyone is concerned about whether or not they should retry after a successful purchase 😁), so I think we need to be able to grab the headers when we hit the `else raise ResponseError.new` path too 🤔
> > I pulled down your branch and did some poking around with `byebug` to confirm my suspicion about the above, and sure enough, if I change the payment method to `@declined_payment_method` in your remote test, then we do skip over the `when 200...300` block of the case statement in `handle_response`, but **only** on the POST to `/payment_intents`.
> > However! The test still passes in that scenario because that purchase request is preceded by a POST to `/payment_methods` (or `/tokens`), and when we handle that initial response, we are storing the headers in the `@response_headers` instance variable. This means those headers are available the second time we go through `add_header_fields`, even though we haven't updated `@response_headers` with info from the second response. A randomly selected txn id that illustrates this kind of sequence is `8Q3Hpae1p6HNz7hLLzB1CJcFkAR`, but I think this would happen to any transaction where we receive a `200` followed by a `402`
> 
> Thanks for pointing out this insight @jcreiff ! Im thinking that with the use case like you mentioned where its most useful for failing transactions, do you think it might be better to move the logic to grab headers only for failing transactions? I think that would be something we can explore instead of adding headers to both fail/successful

thinking more on it, i can just return it on both successful and failures as we are currently digging for a specific header field. I dont think it'll hurt if we implement it this way

2024-07-25 20:59 UTC, jcreiff approved these changes
Thanks for adding the additional tests!

2024-07-26 16:37 UTC, yunnydang commented
thanks Joe! @DustinHaefele would you mind peeking when you have the chance, much appreciated!

2024-07-26 17:34 UTC, DustinHaefele approved these changes

2024-08-01 16:09 UTC, merged