Stripe/StripePI: update add metadata for refund and void
activemerchant/active_merchant pull request #5204
Opened 2024-08-05 21:59 UTC by yunnydang

This change swapsthe add metadata line for refund and void with the add_metadata helper method. Before, we were just adding the entire options[:metadata] object but skipping the order_id. This corrects that to send order_id

Local:
5981 tests, 80146 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Stripe Unit:
147 tests, 777 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Stripe Remote:
78 tests, 333 assertions, 10 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
87.1795% passed

Stripe PI Unit:
62 tests, 319 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Stripe PI Remote:
95 tests, 430 assertions, 3 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
96.8421% passed

2024-08-06 15:45 UTC, jcreiff requested changes

2024-08-06 16:13 UTC, yunnydang commented on test/remote/gateways/remote_stripe_payment_intents_test.rb
> +      order_id: '123445abcde'
done!

2024-08-07 00:44 UTC, jcreiff commented
Hey @yunnydang it looks like the `void` test is failing:

```
Failure: test_create_a_payment_intent_and_void(RemoteStripeIntentsTest)
active_merchant/test/remote/gateways/remote_stripe_payment_intents_test.rb:1291:in `test_create_a_payment_intent_and_void'
     1288:     assert_equal @amount, cancel_response.params.dig('charges', 'data')[0].dig('amount_refunded')
     1289:     assert_equal 'canceled', cancel_response.params['status']
     1290:     assert_equal 'requested_by_customer', cancel_response.params['cancellation_reason']
  => 1291:     assert_equal '123445abcde', cancel_response.params['metadata']['order_id']
     1292:   end
     1293: 
<"123445abcde"> expected but was
<nil>
```

Even though the `add_metadata` logic is shared between the two files for these separate integrations, it looks like only one of the `void` implementations calls it. 

It occurs to me now that we should probably write tests for both Stripe and Stripe PI here, since this change will affect how we send refunds for both

2024-08-07 01:18 UTC, yunnydang commented
> Hey @yunnydang it looks like the `void` test is failing:
> 
> ```
> Failure: test_create_a_payment_intent_and_void(RemoteStripeIntentsTest)
> active_merchant/test/remote/gateways/remote_stripe_payment_intents_test.rb:1291:in `test_create_a_payment_intent_and_void'
>      1288:     assert_equal @amount, cancel_response.params.dig('charges', 'data')[0].dig('amount_refunded')
>      1289:     assert_equal 'canceled', cancel_response.params['status']
>      1290:     assert_equal 'requested_by_customer', cancel_response.params['cancellation_reason']
>   => 1291:     assert_equal '123445abcde', cancel_response.params['metadata']['order_id']
>      1292:   end
>      1293: 
> <"123445abcde"> expected but was
> <nil>
> ```
> 
> Even though the `add_metadata` logic is shared between the two files for these separate integrations, it looks like only one of the `void` implementations calls it.
> 
> It occurs to me now that we should probably write tests for both Stripe and Stripe PI here, since this change will affect how we send refunds for both

interestingly enough the reason that the void test was failing becasue the order_id wasn't being echoed back in the void response

2024-08-12 18:07 UTC, merged