Priority: fix for bin lookup
activemerchant/active_merchant pull request #5366
Opened 2024-12-11 23:12 UTC by Buitragox

Description
-------------------------
Send 8 digits for bin lookups instead of 7.

Unit tests
-------------------------
6157 tests, 80984 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed

Remote tests
-------------------------
31 tests, 84 assertions, 5 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 83.871% passed

Failures not related to changes

Rubocop
-------------------------
808 files inspected, no offenses detected

2024-12-12 20:39 UTC, jherreraa approved these changes
LGTM 👍

2024-12-12 22:39 UTC, sinourain requested changes
Could you please some tests to cover this new case e.g.

`test/remote/gateways/remote_priority_test.rb:327`
```(ruby)
def test_failed_verify
    response = @gateway.verify(@invalid_credit_card)
    assert_failure response
    assert_match 'No bank information found for bin number', response.message
end
```

Maybe an adaptation for unit tests

2024-12-13 20:47 UTC, Buitragox commented
@sinourain Hey I added some unit tests. It was a bit trickier than expected, `verify` also makes an additional request to get a JWT token so that needed to be stubbed as well. Let me know what you think.

2024-12-13 21:37 UTC, sinourain approved these changes
LGTM!

2025-01-08 15:26 UTC, merged